logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ./logs/example.log
      archivedLogFilenamePattern: ./logs/example-%d.log.gz
      archivedFileCount: 5

database:
  driverClass: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://localhost/users?user=root"

# Set up SSL http://www.eclipse.org/jetty/documentation/current/configuring-ssl.html
#server:
#  applicationConnectors:
#    - type: https
#      port: 8443
#      keyStorePath: ${SHOPPING}
#      keyStorePassword: ${SEC_PA1}
#      validateCerts: false